"""Record store implementations and contracts."""

from zeta.records.events import AppendOutcome
from zeta.records.stores.event_store import (
    EventReader,
    EventStoreProtocol,
    EventWriter,
    Filter,
)
from zeta.records.stores.memory import InMemoryStore, MemoryEventStore
from zeta.records.stores.object_store import (
    AmbiguousIdError,
    IncompatibleSchemaError,
    Store,
    StoreBase,
    TraceStats,
    UnknownIdError,
    UnknownSessionError,
    escape_like,
    resolve_object_id,
    warn_trace_failure_once,
)
from zeta.records.stores.sqlite import (
    DEFAULT_SQLITE_NAME,
    EVENT_STORE_NAME,
    ZETA_SQLITE_NAME,
    ZETA_STORE_NAME,
    SqliteEventStore,
    SqliteStore,
    available_session_ids,
    default_sqlite_path,
    event_store_path,
    export_trace_refs,
    import_trace_graph,
    open_existing_trace_store,
    open_trace_store,
    trace_state_dir,
    zeta_sqlite_path,
)

__all__ = [
    "AmbiguousIdError",
    "AppendOutcome",
    "DEFAULT_SQLITE_NAME",
    "EVENT_STORE_NAME",
    "EventReader",
    "EventStoreProtocol",
    "EventWriter",
    "Filter",
    "InMemoryStore",
    "IncompatibleSchemaError",
    "MemoryEventStore",
    "SqliteEventStore",
    "SqliteStore",
    "Store",
    "StoreBase",
    "TraceStats",
    "UnknownIdError",
    "UnknownSessionError",
    "ZETA_SQLITE_NAME",
    "ZETA_STORE_NAME",
    "available_session_ids",
    "default_sqlite_path",
    "escape_like",
    "event_store_path",
    "export_trace_refs",
    "import_trace_graph",
    "open_existing_trace_store",
    "open_trace_store",
    "resolve_object_id",
    "trace_state_dir",
    "warn_trace_failure_once",
    "zeta_sqlite_path",
]
