[package]
name = "zeta-dispatch"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
num-bigint.workspace = true
rusqlite.workspace = true
rustpython-format.workspace = true
serde.workspace = true
serde_json.workspace = true
time.workspace = true
zeta-journal = { path = "../zeta-journal" }
zeta-substrate = { path = "../zeta-substrate" }

[dev-dependencies]
proptest.workspace = true
tempfile.workspace = true
